name: Caravel build
on:
    create:
      tag: [ t* ]
    push:
      branches: [ m* ]
    pull_request:
      branches: [ m* ]
    workflow_dispatch:
      branches: [ m* ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PDK_ROOT:            /home/runner/work/caravel_template/pdks
      OPENLANE_ROOT:       /home/runner/work/caravel_template/openlane
      CARAVEL_ROOT:        /home/runner/work/caravel_template/caravel_template/caravel
      OPENLANE_IMAGE_NAME: efabless/openlane:mpw-3a
      OPENLANE_TAG:        2021.12.17_05.07.41
      CARAVEL_TAG:         mpw-3a
      MAGIC_VERSION:       8.3.209
    steps:
       - uses: actions/checkout@v2
       - name: install deps
         run:  bash ${GITHUB_WORKSPACE}/.github/scripts/build/run-install-magic.sh
       - name: install caravel
         run:  bash ${GITHUB_WORKSPACE}/.github/scripts/build/run-pdk-build.sh
       - name: uncompress
         run:  make uncompress
       - name: build user gds
         run: |
           cd openlane/
           docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_proj -save_path .. -save -tag user_proj -overwrite"
           cd -
       - name: build wrapper gds
         run: |
           cd openlane
           docker run -v $OPENLANE_ROOT:/openLANE_flow -v $PDK_ROOT:$PDK_ROOT -v $PWD/..:/project -v $CARAVEL_ROOT:$CARAVEL_ROOT -e PDK_ROOT=$PDK_ROOT -e CARAVEL_ROOT=$CARAVEL_ROOT -u $(id -u $USER):$(id -g $USER) $OPENLANE_IMAGE_NAME sh -c "cd /project/openlane && flow.tcl -design ./user_project_wrapper -save_path .. -save -tag user_project_wrapper -overwrite"
           cd -
       - name: compress
         run:  make compress
       - name: push
         if: github.event_name == 'create' && github.event.ref_type == 'tag' && startsWith(github.event.ref, 't')
         run: |
           git add def gds lef mag maglef signoff verilog
           git config user.email "rbacik@hotmail.com"
           git config user.name "roman3017"
           git commit -m "tag action: update build"
           git push origin HEAD:main
